version: '3'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: botDb
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  bot:
    build: .
    depends_on:
      - postgres
    environment: {}
    ports:
      - 8000:8000
    volumes:
      - ./strangerchatbot:/strangerchatbot
volumes:
  postgres_data:
