version: '3'

services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: botDb
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  bot:
    build: .
    depends_on:
      - postgres
    volumes:
      - ./strangerchatbot:/strangerchatbot
    environment:
      # Add any environment variables needed for the bot service
    ports:
      # Map any ports if your bot service exposes any
      # - "8000:8000"  # Example if your bot runs on port 8000

volumes:
  postgres_data:
